version: '3.7'
services:
  db:
    build: ./mysql
    image: mysql:8.0.21
    container_name: "mysql-java"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PORT: 3306
      MYSQL_DATABASE: java-db
      TZ: Asia/Tokyo
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default_authentication_plugin=mysql_native_password
    ports:
      - 33336:3306
    volumes:
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/:/etc/mysql/conf.d
